import { Photos } from "./Photos.js";
export const userData = [
	{
		Month: "Jan",
		"Active User": 4000,
	},
	{
		Month: "Feb",
		"Active User": 3000,
	},
	{
		Month: "Mar",
		"Active User": 2000,
	},
	{
		Month: "Apr",
		"Active User": 2780,
	},
	{
		Month: "May",
		"Active User": 1890,
	},
	{
		Month: "Jun",
		"Active User": 2390,
	},
	{
		Month: "Jul",
		"Active User": 3490,
	},
	{
		Month: "Aug",
		"Active User": 6490,
	},
	{
		Month: "Sep",
		"Active User": 2190,
	},
	{
		Month: "Oct",
		"Active User": 3217,
	},
	{
		Month: "Nov",
		"Active User": 1588,
	},
	{
		Month: "Dec",
		"Active User": 7190,
	},
];

export const userRows = [
	{
		id: 1,
		username: "Jon Snow",
		avatar: Photos[0].photo1.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 2,
		username: "Jon Snow",
		avatar: Photos[1].photo2.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 3,
		username: "Jon Snow",
		avatar: Photos[2].photo3.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 4,
		username: "Jon Snow",
		avatar: Photos[3].photo4.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 5,
		username: "Jon Snow",
		avatar: Photos[4].photo5.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 6,
		username: "Jon Snow",
		avatar: Photos[4].photo5.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 7,
		username: "Jon Snow",
		avatar: Photos[3].photo4.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 8,
		username: "Jon Snow",
		avatar: Photos[2].photo3.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 9,
		username: "Jon Snow",
		avatar: Photos[1].photo2.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
	{
		id: 10,
		username: "Jon Snow",
		avatar: Photos[0].photo1.type,
		email: "jon@gmail.com",
		status: "active",
		transaction: "$123.45",
	},
];

export const productRows = [
	{
		id: 1,
		name: "Apple iPhone Pro Max",
		avatar: Photos[0].photo1.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 2,
		name: "Apple iPhone Pro Max",
		avatar: Photos[1].photo2.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 3,
		name: "Apple iPhone Pro Max",
		avatar: Photos[2].photo3.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 4,
		name: "Apple iPhone Pro Max",
		avatar: Photos[3].photo4.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 5,
		name: "Apple iPhone Pro Max",
		avatar: Photos[4].photo5.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 6,
		name: "Apple iPhone Pro Max",
		avatar: Photos[4].photo5.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 7,
		name: "Apple iPhone Pro Max",
		avatar: Photos[3].photo4.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 8,
		name: "Apple iPhone Pro Max",
		avatar: Photos[2].photo3.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 9,
		name: "Apple iPhone Pro Max",
		avatar: Photos[1].photo2.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
	{
		id: 10,
		name: "Apple iPhone Pro Max",
		avatar: Photos[0].photo1.type,
		stock: 111,
		status: "active",
		price: "$123.45",
	},
];
